version: "3.7"

services:
  notebook-server:
    container_name: notebook-server
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - USER_UID=${USER_ID:-1000}
        - USER_GID=${GROUP_ID:-1000}
    volumes:
      - ../notebooks:/notebooks
      - ../:/workspaces/twp

    ports:
      - "8888:8888" # notebook server port
    command: >
      bash -c "pip install -e /workspaces/twp && /start_jupyter_lab.sh"

